import './globals.css'
import '@/assets/font_awesome_6_pro/css/all.min.css'

export const metadata = {
    title: 'MedX',
    description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body suppressHydrationWarning={true}>{children}</body>
        </html>
    )
}
